spring.application.name=Boxing Side App

## MySQL Properties
spring.datasource.url=jdbc:mysql://localhost:3306/boxing_side_app
spring.datasource.username=jerielB
spring.datasource.password=sqlPas$4w0rd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## Server
server.port=9000
